<?php if ($this->breadcrumb) {?>
<ol class="breadcrumb">
    <?php foreach ($this->breadcrumb As $key => $val){?>
    	<?php if ($val['isActive']){?>
    		<li class="active"><?php echo $val['label']?></li>
    	<?php }else{?>
    		<li><a title="<?php echo $val['label']  ?>" href="<?php echo $val['uri']?>"><?php echo $val['label'] ?></a></li>
    	<?php }?>
    <?php }?>
</ol>
<?php }else{?>
	<div class="alert alert-warning" role="alert">
        <?= $this->siteTranslate('tr_site_demo_cms_common_no_result', $this->SiteConfig('default_lang_id'), $this->SiteConfig('site_id')); ?>
	</div>
<?php }?>