<div class="alert alert-success <?php echo ($this->success) ? : 'hidden'?>">
    <?= $this->siteTranslate('tr_site_demo_cms_contact_us_success', $this->SiteConfig('default_lang_id'), $this->SiteConfig('site_id'));?>
</div>
<div class="alert alert-danger <?php echo (!empty($this->errors)) ? : 'hidden'?> ">
	<?= $this->siteTranslate('tr_site_demo_cms_contact_us_failed', $this->SiteConfig('default_lang_id'), $this->SiteConfig('site_id'));?>
</div>

<?php
	$form = $this->prospectsForm;
	$form->prepare();
	echo $this->form()->openTag($form); 
	
	foreach ($form->getElements() As $key => $val)
	{
	    echo '<div class="input-box mb-20">';
    	    $val->setAttribute('class', 'info');
    	    echo $this->formLabel($val);
    	    echo $this->formElement($val, array('class' => 'info'));
	        echo $this->formElementErrors($val, array('class' => 'text-danger'));
	    echo '</div>';
	}
?>
    <div class="row">
        <div class="col-xs-12">
            <div class="input-box">
                <button value="Submit" class="sbumit-btn pull-right" id="submit-contactus-form-btn" data-siteid="<?php echo $this->SiteConfig('news_menu_page_id')?>"><?= $this->siteTranslate('tr_site_demo_cms_common_submit', 1, $this->SiteConfig('site_id'));?></button>
            </div>
        </div>
    </div>
<?php
	echo $this->form()->closeTag(); 
?>
