<div class="delivery-service-area ptb-30">
    <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="single-service shadow-box text-center">
                <!-- <img src="/MelisDemoCmsTwig/images/icons/garantee.png" alt="">
                <h5>Money Back Guarantee</h5> -->
                <img src="/MelisDemoCmsTwig/images/icons/trending.png" alt="">
                <h5>Trending</h5>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="single-service shadow-box text-center">
                <!-- <img src="/MelisDemoCmsTwig/images/icons/coupon.png" alt="">
                <h5>Gift Coupon</h5> -->
                <img src="/MelisDemoCmsTwig/images/icons/news.png" alt="">
                <h5>News</h5>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="single-service shadow-box text-center">
                <!-- <img src="/MelisDemoCmsTwig/images/icons/delivery.png" alt="">
                <h5>Free Shipping</h5> -->
                <img src="/MelisDemoCmsTwig/images/icons/live.png" alt="">
                <h5>Location</h5>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="single-service shadow-box text-center">
                <!-- <img src="/MelisDemoCmsTwig/images/icons/support.png" alt="">
                <h5>24x7 Support</h5> -->
                <img src="/MelisDemoCmsTwig/images/icons/chat.png" alt="">
                <h5>24x7 Support</h5>
            </div>
        </div>
    </div>
</div>
